[package]
name = "openai_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_derive = "*"
http = "*"
serde = "*"
serde_json= "*"
reqwest = {version="*", features=["blocking", "multipart"]}